### ISSUE TITLE
Erreur XeeCloud::pull depuis passage en Debian 10

### ISSUE THREAD

**Issue by djo28** [fgmx85/plugin-XeeCloud#2]
J'ai le message suivant depuis passage en Debian Buster.
`Erreur sur XeeCloud::pull() : Too few arguments to function XeeCloud::pull(), 0 passed in /var/www/html/core/php/jeeCron.php on line 62 and exactly 1 expected`

**Comment by fgmx85** [comment]
La correction viens d’être apportée.

**Comment by djo28** [comment]
Parfait, merci.
